# Generated by Django 5.1.5 on 2025-08-14 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('inspecao', 'Inspeção'), ('avaliacao', 'Avaliação'), ('checklist', 'Checklist'), ('pesquisa', 'Pesquisa'), ('outro', 'Outro')], default='checklist', max_length=50, verbose_name='Tipo')),
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateField(auto_now=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Formulário',
                'verbose_name_plural': 'Formulários',
                'ordering': ['titulo'],
            },
        ),
    ]
