# Generated by Django 5.1.5 on 2025-08-14 21:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoAssistente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo_preferido', models.CharField(choices=[('voice', 'Voz'), ('text', 'Texto')], default='text', max_length=10)),
                ('auto_speak', models.BooleanField(default=True, help_text='Reproduzir respostas em voz automaticamente')),
                ('skills_habilitadas', models.JSONField(default=list, help_text='Lista de skills habilitadas para este usuário')),
                ('configuracoes_avancadas', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Configuração do Assistente',
                'verbose_name_plural': 'Configurações do Assistente',
            },
        ),
        migrations.CreateModel(
            name='ConversaAssistente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('data_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('ativa', models.BooleanField(default=True)),
                ('modo_entrada', models.CharField(choices=[('voice', 'Voz'), ('text', 'Texto')], default='text', max_length=10)),
            ],
            options={
                'verbose_name': 'Conversa com Assistente',
                'verbose_name_plural': 'Conversas com Assistente',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='MemoriaAssistente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=200)),
                ('valor', models.TextField()),
                ('fonte', models.CharField(default='user', max_length=50)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Memória do Assistente',
                'verbose_name_plural': 'Memórias do Assistente',
                'ordering': ['-data_atualizacao'],
            },
        ),
        migrations.CreateModel(
            name='MensagemAssistente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('user', 'Usuário'), ('assistant', 'Assistente'), ('system', 'Sistema')], max_length=10)),
                ('conteudo', models.TextField()),
                ('intencao', models.CharField(blank=True, max_length=100, null=True)),
                ('entidades', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('processado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Mensagem do Assistente',
                'verbose_name_plural': 'Mensagens do Assistente',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SkillExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('parametros', models.JSONField(default=dict)),
                ('resultado', models.TextField(blank=True, null=True)),
                ('sucesso', models.BooleanField(default=False)),
                ('erro', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('tempo_execucao', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Execução de Skill',
                'verbose_name_plural': 'Execuções de Skills',
                'ordering': ['-timestamp'],
            },
        ),
    ]
