# Generated by Django 5.1.5 on 2025-08-14 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistente_web', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoassistente',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_assistente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversaassistente',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversas_assistente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='memoriaassistente',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memorias_assistente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mensagemassistente',
            name='conversa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='assistente_web.conversaassistente'),
        ),
        migrations.AddField(
            model_name='skillexecution',
            name='conversa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execucoes_skills', to='assistente_web.conversaassistente'),
        ),
        migrations.AlterUniqueTogether(
            name='memoriaassistente',
            unique_together={('usuario', 'chave')},
        ),
    ]
