# Generated by Django 5.1.5 on 2025-08-15 13:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('estoque', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='logauditoriaestoque',
            name='evidencias_ids',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logauditoriaestoque',
            name='solicitante_nome_cache',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='logauditoriaestoque',
            name='tipo_especial',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='logauditoriaestoque',
            index=models.Index(fields=['tipo_especial'], name='estoque_log_tipo_es_978769_idx'),
        ),
        migrations.AddIndex(
            model_name='logauditoriaestoque',
            index=models.Index(fields=['hash_atual'], name='estoque_log_hash_at_16779f_idx'),
        ),
    ]
