# Generated by Django 5.1.5 on 2025-08-14 21:56

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConviteUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('tipo_usuario', models.CharField(choices=[('super_admin', 'Super Administrador'), ('admin_empresa', 'Administrador de Empresa'), ('funcionario', 'Funcionário'), ('cliente', 'Cliente'), ('fornecedor', 'Fornecedor'), ('prestador', 'Prestador de Serviço')], max_length=20)),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('nome_completo', models.CharField(blank=True, max_length=255, null=True)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('mensagem_personalizada', models.TextField(blank=True, null=True)),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('aceito_em', models.DateTimeField(blank=True, null=True)),
                ('expirado_em', models.DateTimeField()),
                ('usado', models.BooleanField(default=False)),
                ('enviado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites_enviados', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='convites', to='core.tenant')),
                ('usuario_criado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='convite_origem', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Convite de Usuário',
                'verbose_name_plural': 'Convites de Usuários',
                'ordering': ['-enviado_em'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuarioEstendido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(choices=[('super_admin', 'Super Administrador'), ('admin_empresa', 'Administrador de Empresa'), ('funcionario', 'Funcionário'), ('cliente', 'Cliente'), ('fornecedor', 'Fornecedor'), ('prestador', 'Prestador de Serviço')], default='funcionario', max_length=20)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('suspenso', 'Suspenso'), ('bloqueado', 'Bloqueado'), ('pendente', 'Pendente')], default='pendente', max_length=20)),
                ('avatar', models.ImageField(blank=True, help_text='Foto do perfil do usuário', null=True, upload_to='avatars/')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$', 'CPF deve estar no formato XXX.XXX.XXX-XX')])),
                ('rg', models.CharField(blank=True, max_length=20, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('data_admissao', models.DateField(blank=True, null=True)),
                ('salario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('autenticacao_dois_fatores', models.BooleanField(default=False)),
                ('ultimo_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('tentativas_login_falhadas', models.IntegerField(default=0)),
                ('bloqueado_ate', models.DateTimeField(blank=True, null=True)),
                ('receber_email_notificacoes', models.BooleanField(default=True)),
                ('receber_sms_notificacoes', models.BooleanField(default=False)),
                ('receber_push_notificacoes', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_criados', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_estendido', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='SessaoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('ultima_atividade', models.DateTimeField(auto_now=True)),
                ('ativa', models.BooleanField(default=True)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sessão de Usuário',
                'verbose_name_plural': 'Sessões de Usuários',
                'ordering': ['-ultima_atividade'],
            },
        ),
        migrations.CreateModel(
            name='LogAtividadeUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('modulo', models.CharField(blank=True, max_length=50, null=True)),
                ('objeto_id', models.CharField(blank=True, max_length=50, null=True)),
                ('objeto_tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_atividade', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Atividade',
                'verbose_name_plural': 'Logs de Atividades',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='user_manage_user_id_628fe9_idx'), models.Index(fields=['acao', '-timestamp'], name='user_manage_acao_bf211d_idx')],
            },
        ),
        migrations.CreateModel(
            name='PermissaoPersonalizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(max_length=50)),
                ('acao', models.CharField(max_length=50)),
                ('recurso', models.CharField(blank=True, max_length=100, null=True)),
                ('concedida', models.BooleanField(default=True)),
                ('data_concessao', models.DateTimeField(auto_now_add=True)),
                ('data_expiracao', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('concedida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permissoes_concedidas', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissoes_personalizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permissão Personalizada',
                'verbose_name_plural': 'Permissões Personalizadas',
                'ordering': ['-data_concessao'],
                'unique_together': {('user', 'modulo', 'acao', 'recurso')},
            },
        ),
    ]
