# Generated by Django 5.2.5 on 2025-08-18 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_permissao_scope_tenant'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='permissaopersonalizada',
            name='perm_user_scope_mod_action_idx',
        ),
    ]
