# Generated by Django 5.2.5 on 2025-08-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_remove_permissaopersonalizada_perm_user_scope_mod_action_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuarioestendido',
            name='failed_2fa_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perfilusuarioestendido',
            name='totp_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuarioestendido',
            name='totp_recovery_codes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='perfilusuarioestendido',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
