# Generated by Django 5.2.5 on 2025-08-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_twofa_lock_and_encrypt_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuarioestendido',
            name='twofa_failure_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perfilusuarioestendido',
            name='twofa_recovery_use_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perfilusuarioestendido',
            name='twofa_success_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
