# Generated by Django 5.2.5 on 2025-08-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0006_perfilusuarioestendido_twofa_failure_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuarioestendido',
            name='twofa_rate_limit_block_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
