# Generated by Django 5.2.5 on 2025-09-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0010_alter_sessaousuario_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logatividadeusuario',
            name='ip_address',
            field=models.GenericIPAddressField(),
        ),
    ]
