# Generated by Django 5.2.5 on 2025-09-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0011_alter_logatividadeusuario_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='logatividadeusuario',
            name='extra_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
