# Generated by Django 5.1.5 on 2025-08-14 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlvoAplicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Alvo de Aplicação',
                'verbose_name_plural': 'Alvos de Aplicação',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaAuxiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='Slug')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Categoria Auxiliar',
                'verbose_name_plural': 'Categorias Auxiliares',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='UnidadeMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome da Unidade')),
                ('simbolo', models.CharField(max_length=10, unique=True, verbose_name='Símbolo / Sigla')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Unidade de Medida',
                'verbose_name_plural': 'Unidades de Medida',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ItemAuxiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=120, verbose_name='Slug')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('alvo', models.CharField(choices=[('cliente', 'Cliente'), ('fornecedor', 'Fornecedor'), ('funcionario', 'Funcionário'), ('empresa', 'Empresa/Tenant'), ('produto', 'Produto'), ('servico', 'Serviço'), ('outro', 'Outro')], default='outro', max_length=20, verbose_name='Alvo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Configuração (JSON)')),
                ('versionavel', models.BooleanField(default=False, verbose_name='Versionável')),
                ('periodicidade', models.CharField(choices=[('nenhuma', 'Nenhuma'), ('mensal', 'Mensal'), ('anual', 'Anual')], default='nenhuma', max_length=10, verbose_name='Periodicidade')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='cadastros_gerais.categoriaauxiliar', verbose_name='Categoria')),
                ('targets', models.ManyToManyField(blank=True, related_name='itens', to='cadastros_gerais.alvoaplicacao', verbose_name='Aplicar em')),
            ],
            options={
                'verbose_name': 'Item Auxiliar',
                'verbose_name_plural': 'Itens Auxiliares',
                'ordering': ['categoria__nome', 'ordem', 'nome'],
                'unique_together': {('categoria', 'slug')},
            },
        ),
    ]
