services:
  - type: web
    name: sitema-pandora
    runtime: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /
    dockerfilePath: Dockerfile
    dockerContext: .
    envVars:
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: "3"
      - key: DATABASE_URL
        fromDatabase:
          name: sitema-pandora-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: sitema-pandora-redis
          type: redis
      - key: RENDER_EXTERNAL_URL
        fromService:
          name: sitema-pandora
          type: web
  - type: redis
    name: sitema-pandora-redis
    plan: free
    ipAllowList: []

databases:
  - name: sitema-pandora-db
    plan: free
  
  
  
  
  
  
  


