# Generated by Django 5.1.5 on 2025-08-14 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('tipo', models.CharField(choices=[('financeiro', 'Financeiro'), ('obra', 'Obra'), ('estoque', 'Estoque'), ('funcionarios', 'Funcionários'), ('clientes', 'Clientes'), ('personalizado', 'Personalizado')], default='personalizado', max_length=50, verbose_name='Tipo')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='relatorios/', verbose_name='Arquivo')),
            ],
            options={
                'verbose_name': 'Relatório',
                'verbose_name_plural': 'Relatórios',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
