# Generated by ChatGPT on 2025-09-16
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_cargo_tenantuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.department', verbose_name='Departamento'),
        ),
    ]
