# Generated by Django 5.1.5 on 2025-08-14 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoSST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('procedimento', 'Procedimento de Segurança'), ('analise_risco', 'Análise de Risco'), ('treinamento', 'Registro de Treinamento'), ('acidente', 'Registro de Acidente'), ('epi', 'Controle de EPI'), ('outro', 'Outro')], default='procedimento', max_length=50, verbose_name='Tipo')),
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateField(auto_now=True, verbose_name='Data de Atualização')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='sst_documentos/', verbose_name='Arquivo')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_sst', to='funcionarios.funcionario', verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Documento SST',
                'verbose_name_plural': 'Documentos SST',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
