# Generated by ChatGPT assistant
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0011_funcionarioremuneracaoregra'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='motivo_demissao',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo da Demissão/Desligamento'),
        ),
    ]
