# Generated by Django 5.2.5 on 2025-08-20 14:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fornecedores', '0002_add_portal_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcessoFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('is_admin_portal', models.BooleanField(default=False, help_text='Usuário pode gerenciar outros usuários do fornecedor', verbose_name='Administrador do Portal')),
                ('ativo', models.BooleanField(default=True, help_text='Acesso ativo ao portal', verbose_name='Ativo')),
                ('data_concessao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Concessão')),
                ('data_ultimo_acesso', models.DateTimeField(blank=True, null=True, verbose_name='Último Acesso')),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre o acesso', verbose_name='Observações')),
                ('concedido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acessos_fornecedor_concedidos', to=settings.AUTH_USER_MODEL, verbose_name='Concedido por')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acessos', to='fornecedores.fornecedor', verbose_name='Fornecedor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acessos_fornecedor', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Acesso de Fornecedor',
                'verbose_name_plural': 'Acessos de Fornecedores',
                'db_table': 'portal_fornecedor_acesso',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['fornecedor', 'ativo'], name='portal_forn_fornece_05f4c4_idx'), models.Index(fields=['usuario', 'ativo'], name='portal_forn_usuario_434326_idx')],
                'constraints': [models.UniqueConstraint(fields=('fornecedor', 'usuario'), name='unique_acesso_fornecedor_usuario')],
            },
        ),
    ]
