# Generated by Django 5.1.5 on 2025-08-14 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Categoria')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Categoria de Documento',
                'verbose_name_plural': 'Categorias de Documento',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Documento')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('periodicidade', models.CharField(choices=[('unico', 'Único'), ('mensal', 'Mensal'), ('anual', 'Anual'), ('eventual', 'Eventual')], default='unico', max_length=10, verbose_name='Periodicidade')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('versionavel', models.BooleanField(default=True, verbose_name='Versionável')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos', to='documentos.categoriadocumento', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documento',
                'ordering': ['categoria__ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidade_object_id', models.PositiveIntegerField()),
                ('periodicidade_aplicada', models.CharField(blank=True, choices=[('unico', 'Único'), ('mensal', 'Mensal'), ('anual', 'Anual'), ('eventual', 'Eventual')], help_text='Se vazio usa a do tipo/regra', max_length=10, null=True, verbose_name='Periodicidade Aplicada')),
                ('obrigatorio', models.BooleanField(default=True, verbose_name='Obrigatório')),
                ('observacao', models.CharField(blank=True, max_length=255, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('entidade_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='documentos.tipodocumento', verbose_name='Tipo de Documento')),
            ],
            options={
                'verbose_name': 'Documento Associado',
                'verbose_name_plural': 'Documentos Associados',
                'unique_together': {('entidade_content_type', 'entidade_object_id', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='DocumentoVersao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='documentos/')),
                ('competencia', models.CharField(blank=True, help_text='MM/AAAA se aplicável', max_length=7)),
                ('observacao', models.CharField(blank=True, max_length=255, verbose_name='Observação')),
                ('enviado_em', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('versao', models.PositiveIntegerField(default=1, verbose_name='Versão')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado'), ('vencido', 'Vencido')], default='pendente', max_length=20, verbose_name='Status')),
                ('validade_data', models.DateField(blank=True, null=True, verbose_name='Validade')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versoes', to='documentos.documento', verbose_name='Documento')),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Versão de Documento',
                'verbose_name_plural': 'Versões de Documento',
                'ordering': ['-enviado_em', '-versao'],
                'unique_together': {('documento', 'competencia', 'versao')},
            },
        ),
        migrations.CreateModel(
            name='RegraDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escopo', models.CharField(choices=[('app', 'Todos do Módulo/App'), ('filtro', 'Filtro por Atributos'), ('entidade', 'Somente uma Entidade')], default='entidade', max_length=20, verbose_name='Escopo')),
                ('app_label', models.CharField(blank=True, max_length=50, null=True, verbose_name='App Label')),
                ('entidade_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID Entidade')),
                ('nivel_aplicacao', models.CharField(choices=[('entidade', 'Entidade (direto)'), ('subentidades', 'Subentidades (ex: Funcionários)')], default='entidade', max_length=20, verbose_name='Nível de Aplicação')),
                ('periodicidade_override', models.CharField(blank=True, choices=[('unico', 'Único'), ('mensal', 'Mensal'), ('anual', 'Anual'), ('eventual', 'Eventual')], max_length=10, null=True, verbose_name='Periodicidade (Override)')),
                ('exigencia', models.CharField(choices=[('obrigatorio', 'Obrigatório'), ('recomendado', 'Recomendado'), ('opcional', 'Opcional')], default='obrigatorio', max_length=20, verbose_name='Exigência')),
                ('validade_dias', models.PositiveIntegerField(blank=True, help_text='Se informado, calcula vencimento automático', null=True, verbose_name='Validade (dias)')),
                ('data_base', models.DateField(blank=True, null=True, verbose_name='Data Base')),
                ('filtro_tipo_fornecimento', models.CharField(blank=True, choices=[('PRODUTOS', 'Produtos'), ('SERVICOS', 'Serviços'), ('AMBOS', 'Ambos')], max_length=10, null=True, verbose_name='Tipo de Fornecimento (Filtro)')),
                ('observacoes', models.CharField(blank=True, max_length=255, verbose_name='Observações')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('entidade_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Entidade')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras', to='documentos.tipodocumento', verbose_name='Tipo de Documento')),
            ],
            options={
                'verbose_name': 'Regra de Documento',
                'verbose_name_plural': 'Regras de Documentos',
                'ordering': ['tipo__nome'],
                'indexes': [models.Index(fields=['entidade_content_type', 'entidade_object_id'], name='documentos__entidad_752956_idx'), models.Index(fields=['ativo'], name='documentos__ativo_276542_idx'), models.Index(fields=['app_label'], name='documentos__app_lab_94ee2e_idx'), models.Index(fields=['escopo'], name='documentos__escopo_cf646e_idx')],
            },
        ),
    ]
