# Generated by Django 5.2.5 on 2025-09-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_dominio_status_regra'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='regradocumento',
            new_name='documentos__status_c37e99_idx',
            old_name='documentos_regra_status_idx',
        ),
        migrations.RenameIndex(
            model_name='regradocumento',
            new_name='documentos__dominio_49c8f9_idx',
            old_name='documentos_regra_dominio_idx',
        ),
        migrations.AlterField(
            model_name='dominiodocumento',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='regradocumento',
            name='app_label',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='App Label (Legado)'),
        ),
        migrations.AddIndex(
            model_name='dominiodocumento',
            index=models.Index(fields=['slug'], name='documentos__slug_ba98c1_idx'),
        ),
        migrations.AddIndex(
            model_name='dominiodocumento',
            index=models.Index(fields=['app_label'], name='documentos__app_lab_b970b0_idx'),
        ),
        migrations.AddIndex(
            model_name='dominiodocumento',
            index=models.Index(fields=['ativo'], name='documentos__ativo_66aa72_idx'),
        ),
    ]
