# Generated by Django 5.2.5 on 2025-09-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0004_regra_add_tenant_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regradocumento',
            name='escopo',
            field=models.CharField(choices=[('app', 'Global (Todos Tenants)'), ('tenant', 'Tenant (Empresa)'), ('filtro', 'Filtro por Atributos'), ('entidade', 'Somente uma Entidade')], default='entidade', max_length=20, verbose_name='Escopo'),
        ),
    ]
