# Generated by Django 5.2.5 on 2025-09-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0006_wizardtenantdocumentotemp'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='wizardtenantdocumentotemp',
            new_name='documentos__tenant__eeef5e_idx',
            old_name='documentos_tenant_sess_idx',
        ),
        migrations.RenameIndex(
            model_name='wizardtenantdocumentotemp',
            new_name='documentos__tipo_id_33ab02_idx',
            old_name='documentos_tipo_idx',
        ),
        migrations.AlterField(
            model_name='regradocumento',
            name='escopo',
            field=models.CharField(choices=[('app', 'Plataforma (todos os tenants)'), ('tenant', 'Empresa (tenant atual)'), ('filtro', 'Filtro avançado'), ('entidade', 'Entidade específica')], default='entidade', max_length=20, verbose_name='Escopo'),
        ),
        migrations.AlterField(
            model_name='wizardtenantdocumentotemp',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
