# Generated by Django 5.1.5 on 2025-08-14 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaConfiguracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lembretes_padrao', models.JSONField(blank=True, default=list)),
                ('digest_email_habilitado', models.BooleanField(default=False)),
                ('digest_email_hora', models.PositiveSmallIntegerField(default=8)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração da Agenda',
                'verbose_name_plural': 'Configurações da Agenda',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('data_inicio', models.DateTimeField(verbose_name='Data e Hora de Início')),
                ('data_fim', models.DateTimeField(blank=True, null=True, verbose_name='Data e Hora de Fim')),
                ('dia_inteiro', models.BooleanField(default=False, verbose_name='Dia Inteiro')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('realizado', 'Realizado'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='pendente', max_length=10, verbose_name='Status')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10, verbose_name='Prioridade')),
                ('local', models.CharField(blank=True, max_length=255, null=True, verbose_name='Local')),
                ('tipo_evento', models.CharField(choices=[('empresa', 'Evento da Empresa'), ('cliente', 'Evento de Cliente'), ('atendimento', 'Agendamento de Atendimento'), ('fornecedor', 'Evento com Fornecedor'), ('funcionario', 'Evento Interno (Funcionário)'), ('procedimento', 'Agendamento de Procedimento'), ('outro', 'Outro')], default='outro', max_length=20, verbose_name='Tipo de Evento')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='EventoLembrete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutos_antes', models.PositiveIntegerField(default=15, help_text='Minutos antes do início do evento')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lembrete de Evento',
                'verbose_name_plural': 'Lembretes de Eventos',
            },
        ),
        migrations.CreateModel(
            name='LogEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=255, verbose_name='Ação')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora')),
            ],
            options={
                'verbose_name': 'Log de Evento',
                'verbose_name_plural': 'Logs de Eventos',
                'ordering': ['-data_hora'],
            },
        ),
    ]
