# Generated by Django 5.2.5 on 2025-08-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_evento_status_agendado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='prioridade',
            field=models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica'), ('urgente', 'Urgente')], default='media', max_length=10, verbose_name='Prioridade'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='tipo_evento',
            field=models.CharField(choices=[('empresa', 'Evento da Empresa'), ('cliente', 'Evento de Cliente'), ('atendimento', 'Agendamento de Atendimento'), ('reuniao', 'Reunião'), ('fornecedor', 'Evento com Fornecedor'), ('funcionario', 'Evento Interno (Funcionário)'), ('procedimento', 'Agendamento de Procedimento'), ('outro', 'Outro')], default='outro', max_length=20, verbose_name='Tipo de Evento'),
        ),
    ]
