# Generated by Django 5.2.5 on 2025-09-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_alter_evento_prioridade_alter_evento_tipo_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='tipo_evento',
            field=models.CharField(choices=[('empresa', 'Evento da Empresa'), ('cliente', 'Evento de Cliente'), ('atendimento', 'Agendamento de Atendimento'), ('servico', 'Agendamento de Serviço'), ('reuniao', 'Reunião'), ('fornecedor', 'Evento com Fornecedor'), ('funcionario', 'Evento Interno (Funcionário)'), ('outro', 'Outro')], default='outro', max_length=20, verbose_name='Tipo de Evento'),
        ),
    ]
