# Generated by Django 5.1.5 on 2025-08-14 21:56

import django.db.models.deletion
import produtos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros_gerais', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filhas', to='produtos.categoria')),
            ],
            options={
                'verbose_name': 'Categoria de Produto',
                'verbose_name_plural': 'Categorias de Produtos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Produto')),
                ('sku', models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='SKU')),
                ('codigo', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código Legado')),
                ('codigo_barras', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código de Barras')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('especificacoes_tecnicas', models.TextField(blank=True, null=True, verbose_name='Especificações Técnicas')),
                ('tipo', models.CharField(choices=[('SIMPLES', 'Simples'), ('VARIANTE_PAI', 'Variante (Pai)'), ('VARIANTE', 'Variante')], default='SIMPLES', max_length=15)),
                ('preco_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço Unitário')),
                ('preco_custo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço de Custo')),
                ('tipo_custo', models.CharField(choices=[('preco_medio', 'Preço Médio Ponderado'), ('peps', 'PEPS (FIFO)'), ('custo_padrao', 'Custo Padrão'), ('especifico', 'Custo Específico')], default='preco_medio', max_length=20, verbose_name='Tipo de Custo')),
                ('margem_lucro', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Margem de Lucro (%)')),
                ('estoque_atual', models.PositiveIntegerField(default=0, verbose_name='Quantidade em Estoque')),
                ('estoque_minimo', models.PositiveIntegerField(default=0, verbose_name='Estoque Mínimo')),
                ('estoque_maximo', models.PositiveIntegerField(default=0, verbose_name='Estoque Máximo')),
                ('controla_estoque', models.BooleanField(default=True, verbose_name='Controla Estoque')),
                ('controla_lote', models.BooleanField(default=False, verbose_name='Controla por Lote')),
                ('controla_numero_serie', models.BooleanField(default=False, verbose_name='Controla por Nº de Série')),
                ('imagem_principal', models.ImageField(blank=True, null=True, upload_to='produtos/principais/', verbose_name='Imagem Principal')),
                ('ncm', models.CharField(blank=True, max_length=10, null=True, verbose_name='NCM')),
                ('peso', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Peso (kg)')),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Altura (cm)')),
                ('largura', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Largura (cm)')),
                ('profundidade', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Profundidade (cm)')),
                ('fabricante', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fabricante')),
                ('marca', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo')),
                ('garantia', models.CharField(blank=True, max_length=50, null=True, verbose_name='Garantia')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('status_ciclo', models.CharField(choices=[('ATIVO', 'Ativo'), ('SUSPENSO', 'Suspenso'), ('DESCONTINUADO', 'Descontinuado')], default='ATIVO', max_length=15)),
                ('destaque', models.BooleanField(default=False, verbose_name='Produto em Destaque')),
                ('data_cadastro', models.DateField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.categoria', verbose_name='Categoria')),
                ('produto_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='produtos.produto')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros_gerais.unidademedida', verbose_name='Unidade de Medida')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ProdutoAtributoDef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True)),
                ('tipo', models.CharField(choices=[('texto', 'Texto'), ('num', 'Numérico'), ('bool', 'Booleano'), ('lista', 'Lista'), ('json', 'JSON')], default='texto', max_length=10)),
                ('obrigatorio', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros_gerais.unidademedida')),
            ],
            options={
                'verbose_name': 'Definição Atributo Produto',
                'verbose_name_plural': 'Definições Atributos Produto',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ProdutoAtributoValor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_textual', models.CharField(blank=True, max_length=255, null=True)),
                ('valor_num', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('valor_json', models.JSONField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atributo_def', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='produtos.produtoatributodef')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atributos_valores', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Valor Atributo Produto',
                'verbose_name_plural': 'Valores Atributos Produto',
            },
        ),
        migrations.CreateModel(
            name='ProdutoBOMItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_por_unidade', models.DecimalField(decimal_places=6, max_digits=14)),
                ('perda_perc', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='como_componente', to='produtos.produto')),
                ('produto_pai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_itens', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Item BOM',
                'verbose_name_plural': 'Itens BOM',
            },
        ),
        migrations.CreateModel(
            name='ProdutoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('arquivo', models.FileField(upload_to='produtos/documentos/', verbose_name='Arquivo')),
                ('tipo', models.CharField(choices=[('manual', 'Manual'), ('certificado', 'Certificado'), ('ficha_tecnica', 'Ficha Técnica'), ('outro', 'Outro')], default='outro', max_length=50, verbose_name='Tipo de Documento')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Documento do Produto',
                'verbose_name_plural': 'Documentos do Produto',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='ProdutoImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to=produtos.models.produto_imagem_path, verbose_name='Imagem')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Título')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Imagem do Produto',
                'verbose_name_plural': 'Imagens do Produto',
                'ordering': ['ordem', 'data_upload'],
            },
        ),
        migrations.CreateModel(
            name='ProdutoVariacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Variação')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descrição')),
                ('preco_adicional', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço Adicional')),
                ('estoque', models.PositiveIntegerField(default=0, verbose_name='Estoque')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variacoes', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Variação do Produto',
                'verbose_name_plural': 'Variações do Produto',
                'ordering': ['nome'],
            },
        ),
        migrations.AddIndex(
            model_name='categoria',
            index=models.Index(fields=['parent', 'nome'], name='produtos_ca_parent__fcca6d_idx'),
        ),
        migrations.AddIndex(
            model_name='produtoatributovalor',
            index=models.Index(fields=['produto', 'atributo_def'], name='prod_attr_prod_def_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='produtoatributovalor',
            unique_together={('produto', 'atributo_def')},
        ),
        migrations.AddIndex(
            model_name='produtobomitem',
            index=models.Index(fields=['produto_pai'], name='bom_prod_pai_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='produtobomitem',
            unique_together={('produto_pai', 'componente')},
        ),
    ]
