# Generated by Django 5.2.5 on 2025-08-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='data_ativacao_portal',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Ativação do Portal'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='portal_ativo',
            field=models.BooleanField(default=False, help_text='Permite acesso ao portal do fornecedor', verbose_name='Portal Ativo'),
        ),
    ]
