# Generated by Django 5.1.5 on 2025-08-14 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetoQuantificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Projeto')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_previsao_conclusao', models.DateField(blank=True, null=True, verbose_name='Previsão de Conclusão')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='rascunho', max_length=50, verbose_name='Status')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos_quantificacao_responsavel', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos_quantificacao', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Projeto de Quantificação',
                'verbose_name_plural': 'Projetos de Quantificação',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemQuantificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Item')),
                ('unidade_medida', models.CharField(max_length=50, verbose_name='Unidade de Medida')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade')),
                ('custo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Custo Unitário')),
                ('custo_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Custo Total')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('tipo_item', models.CharField(choices=[('material', 'Material'), ('mao_de_obra', 'Mão de Obra'), ('equipamento', 'Equipamento'), ('servico', 'Serviço'), ('outro', 'Outro')], default='material', max_length=50, verbose_name='Tipo de Item')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_quantificacao', to='quantificacao_obras.projetoquantificacao')),
            ],
            options={
                'verbose_name': 'Item de Quantificação',
                'verbose_name_plural': 'Itens de Quantificação',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnexoQuantificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('nome_arquivo', models.CharField(max_length=255, verbose_name='Nome do Arquivo')),
                ('arquivo', models.FileField(upload_to='quantificacao_anexos/', verbose_name='Arquivo')),
                ('tipo_arquivo', models.CharField(blank=True, max_length=100, verbose_name='Tipo de Arquivo')),
                ('tamanho_arquivo', models.BigIntegerField(blank=True, null=True, verbose_name='Tamanho (bytes)')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('upload_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anexos_quantificacao_upload', to=settings.AUTH_USER_MODEL)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos_quantificacao', to='quantificacao_obras.projetoquantificacao')),
            ],
            options={
                'verbose_name': 'Anexo de Quantificação',
                'verbose_name_plural': 'Anexos de Quantificação',
                'ordering': ['-created_at'],
            },
        ),
    ]
