# Generated by Django 5.1.5 on 2025-08-14 21:56

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('tamanho_maximo_arquivo_mb', models.PositiveIntegerField(default=10, verbose_name='Tamanho Máximo de Arquivo (MB)')),
                ('tipos_arquivo_permitidos', models.JSONField(blank=True, default=list, verbose_name='Tipos de Arquivo Permitidos')),
                ('dias_retencao_mensagens', models.PositiveIntegerField(default=365, verbose_name='Dias de Retenção de Mensagens')),
                ('moderacao_habilitada', models.BooleanField(default=False, verbose_name='Moderação Habilitada')),
                ('palavras_bloqueadas', models.JSONField(blank=True, default=list, verbose_name='Palavras Bloqueadas')),
                ('notificacoes_push_habilitadas', models.BooleanField(default=True, verbose_name='Push Notifications Habilitadas')),
                ('notificacoes_email_habilitadas', models.BooleanField(default=False, verbose_name='Notificações por E-mail Habilitadas')),
            ],
            options={
                'verbose_name': 'Configuração do Chat',
                'verbose_name_plural': 'Configurações do Chat',
            },
        ),
        migrations.CreateModel(
            name='Conversa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('titulo', models.CharField(blank=True, max_length=200, verbose_name='Título')),
                ('tipo', models.CharField(choices=[('individual', 'Individual'), ('grupo', 'Grupo')], default='individual', max_length=15, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('arquivada', 'Arquivada'), ('bloqueada', 'Bloqueada')], default='ativa', max_length=15, verbose_name='Status')),
                ('ultima_atividade', models.DateTimeField(auto_now=True, verbose_name='Última Atividade')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Conversa',
                'verbose_name_plural': 'Conversas',
                'ordering': ['-ultima_atividade'],
            },
        ),
        migrations.CreateModel(
            name='ConversaFavorita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogMensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=255, verbose_name='Ação')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora')),
            ],
            options={
                'verbose_name': 'Log de Mensagem',
                'verbose_name_plural': 'Logs de Mensagens',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('tipo', models.CharField(choices=[('texto', 'Texto'), ('arquivo', 'Arquivo'), ('imagem', 'Imagem'), ('sistema', 'Sistema')], default='texto', max_length=10, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('enviada', 'Enviada'), ('entregue', 'Entregue'), ('lida', 'Lida'), ('editada', 'Editada'), ('excluida', 'Excluída')], default='enviada', max_length=10, verbose_name='Status')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='chat/arquivos/%Y/%m/', verbose_name='Arquivo')),
                ('nome_arquivo_original', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Original do Arquivo')),
                ('lida', models.BooleanField(default=False, verbose_name='Lida')),
                ('data_leitura', models.DateTimeField(blank=True, null=True, verbose_name='Data de Leitura')),
                ('data_edicao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Edição')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MensagemFixada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MensagemReacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipanteConversa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('data_entrada', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Entrada')),
                ('data_saida', models.DateTimeField(blank=True, null=True, verbose_name='Data de Saída')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ultima_visualizacao', models.DateTimeField(blank=True, null=True, verbose_name='Última Visualização')),
                ('notificacoes_habilitadas', models.BooleanField(default=True, verbose_name='Notificações Habilitadas')),
            ],
            options={
                'verbose_name': 'Participante da Conversa',
                'verbose_name_plural': 'Participantes das Conversas',
            },
        ),
        migrations.CreateModel(
            name='PreferenciaUsuarioChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('notificacoes_habilitadas', models.BooleanField(default=True, verbose_name='Notificações Habilitadas')),
                ('som_notificacao_habilitado', models.BooleanField(default=True, verbose_name='Som de Notificação Habilitado')),
                ('status_online_visivel', models.BooleanField(default=True, verbose_name='Status Online Visível')),
                ('ultima_visualizacao_visivel', models.BooleanField(default=True, verbose_name='Última Visualização Visível')),
                ('tema_escuro', models.BooleanField(default=False, verbose_name='Tema Escuro')),
                ('tamanho_fonte', models.CharField(choices=[('pequeno', 'Pequeno'), ('medio', 'Médio'), ('grande', 'Grande')], default='medio', max_length=10, verbose_name='Tamanho da Fonte')),
            ],
            options={
                'verbose_name': 'Preferência de Chat do Usuário',
                'verbose_name_plural': 'Preferências de Chat dos Usuários',
            },
        ),
    ]
