# Generated by Django 5.1.5 on 2025-08-14 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaochat',
            name='tenant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracao_chat', to='core.tenant', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='conversa',
            name='criador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversas_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criador'),
        ),
        migrations.AddField(
            model_name='conversa',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversas', to='core.tenant', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='conversafavorita',
            name='conversa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='chat.conversa'),
        ),
        migrations.AddField(
            model_name='conversafavorita',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversas_favoritas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logmensagem',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='conversa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='chat.conversa', verbose_name='Conversa'),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='remetente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_enviadas_chat', to=settings.AUTH_USER_MODEL, verbose_name='Remetente'),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='resposta_para',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respostas', to='chat.mensagem', verbose_name='Resposta Para'),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_chat', to='core.tenant', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='logmensagem',
            name='mensagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='chat.mensagem', verbose_name='Mensagem'),
        ),
        migrations.AddField(
            model_name='mensagemfixada',
            name='conversa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_fixadas', to='chat.conversa'),
        ),
        migrations.AddField(
            model_name='mensagemfixada',
            name='fixada_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensagens_fixadas_acao', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mensagemfixada',
            name='mensagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixacoes', to='chat.mensagem'),
        ),
        migrations.AddField(
            model_name='mensagemreacao',
            name='mensagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reacoes', to='chat.mensagem'),
        ),
        migrations.AddField(
            model_name='mensagemreacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reacoes_mensagem', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='participanteconversa',
            name='adicionado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participantes_adicionados', to=settings.AUTH_USER_MODEL, verbose_name='Adicionado Por'),
        ),
        migrations.AddField(
            model_name='participanteconversa',
            name='conversa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes_detalhes', to='chat.conversa', verbose_name='Conversa'),
        ),
        migrations.AddField(
            model_name='participanteconversa',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacoes_conversa', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='conversa',
            name='participantes',
            field=models.ManyToManyField(related_name='conversas_participando', through='chat.ParticipanteConversa', to=settings.AUTH_USER_MODEL, verbose_name='Participantes'),
        ),
        migrations.AddField(
            model_name='preferenciausuariochat',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencia_chat', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddIndex(
            model_name='conversafavorita',
            index=models.Index(fields=['usuario', 'conversa'], name='chat_conver_usuario_e510e3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conversafavorita',
            unique_together={('usuario', 'conversa')},
        ),
        migrations.AddIndex(
            model_name='mensagem',
            index=models.Index(fields=['conversa', 'created_at'], name='chat_mensag_convers_0e9a47_idx'),
        ),
        migrations.AddIndex(
            model_name='mensagem',
            index=models.Index(fields=['remetente', 'created_at'], name='chat_mensag_remeten_3882d4_idx'),
        ),
        migrations.AddIndex(
            model_name='mensagem',
            index=models.Index(fields=['tenant', 'status'], name='chat_mensag_tenant__0b0662_idx'),
        ),
        migrations.AddIndex(
            model_name='mensagem',
            index=models.Index(fields=['lida', 'created_at'], name='chat_mensag_lida_e8a26b_idx'),
        ),
        migrations.AddIndex(
            model_name='mensagemfixada',
            index=models.Index(fields=['conversa', 'created_at'], name='chat_mensag_convers_af3717_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mensagemfixada',
            unique_together={('conversa', 'mensagem')},
        ),
        migrations.AddIndex(
            model_name='mensagemreacao',
            index=models.Index(fields=['mensagem', 'emoji'], name='chat_mensag_mensage_ce4695_idx'),
        ),
        migrations.AddIndex(
            model_name='mensagemreacao',
            index=models.Index(fields=['usuario'], name='chat_mensag_usuario_989d56_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mensagemreacao',
            unique_together={('mensagem', 'usuario', 'emoji')},
        ),
        migrations.AlterUniqueTogether(
            name='participanteconversa',
            unique_together={('conversa', 'usuario')},
        ),
        migrations.AddIndex(
            model_name='conversa',
            index=models.Index(fields=['tenant', 'status'], name='chat_conver_tenant__23c6de_idx'),
        ),
        migrations.AddIndex(
            model_name='conversa',
            index=models.Index(fields=['tenant', 'tipo'], name='chat_conver_tenant__63f4ea_idx'),
        ),
        migrations.AddIndex(
            model_name='conversa',
            index=models.Index(fields=['ultima_atividade'], name='chat_conver_ultima__bd732b_idx'),
        ),
    ]
