# Generated by Django 5.2.5 on 2025-08-18 14:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversa',
            name='participantes',
            field=models.ManyToManyField(related_name='conversas_participando', through='chat.ParticipanteConversa', through_fields=('conversa', 'usuario'), to=settings.AUTH_USER_MODEL, verbose_name='Participantes'),
        ),
    ]
