# Generated by Django 5.1.5 on 2025-08-14 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Indicador')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor')),
                ('meta', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Meta')),
                ('data', models.DateField(verbose_name='Data')),
                ('tipo', models.CharField(choices=[('financeiro', 'Financeiro'), ('produtividade', 'Produtividade'), ('qualidade', 'Qualidade'), ('eficiencia', 'Eficiência'), ('vendas', 'Vendas'), ('marketing', 'Marketing'), ('operacional', 'Operacional'), ('rh', 'Recursos Humanos'), ('outro', 'Outro')], default='outro', max_length=50, verbose_name='Tipo')),
                ('periodo', models.CharField(choices=[('diario', 'Diário'), ('semanal', 'Semanal'), ('mensal', 'Mensal'), ('trimestral', 'Trimestral'), ('anual', 'Anual')], default='mensal', max_length=50, verbose_name='Período')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('arquivado', 'Arquivado')], default='ativo', max_length=20, verbose_name='Status')),
                ('unidade_medida', models.CharField(blank=True, max_length=50, null=True, verbose_name='Unidade de Medida')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Indicador',
                'verbose_name_plural': 'Indicadores',
                'ordering': ['-data', 'nome'],
            },
        ),
    ]
