# Generated by Django 5.2.5 on 2025-08-22 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0004_remover_tipo_servico'),
        ('prontuarios', '0012_atendimento_agendamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='procedimento',
            field=models.ForeignKey(blank=True, help_text='Procedimento clínico associado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos', to='prontuarios.procedimento'),
        ),
    ]
