# Generated by Django 5.2.5 on 2025-09-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0006_profissional_procedimento'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='profissionalprocedimento',
            new_name='agendamento_tenant__57e65b_idx',
            old_name='agendam_profc_tenant_prof_idx',
        ),
        migrations.RenameIndex(
            model_name='profissionalprocedimento',
            new_name='agendamento_tenant__b551ff_idx',
            old_name='agendam_profc_tenant_proc_idx',
        ),
        migrations.AlterField(
            model_name='profissionalprocedimento',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='profissionalprocedimento',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de atualização'),
        ),
    ]
