# Generated by Django 5.2.5 on 2025-09-10 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0007_rename_agendam_profc_tenant_prof_idx_agendamento_tenant__57e65b_idx_and_more'),
        ('servicos', '0003_migrate_procedimentos_to_servicos'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='servico',
            field=models.ForeignKey(blank=True, help_text='Novo campo de serviço unificado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos', to='servicos.servico'),
        ),
        migrations.AddField(
            model_name='profissionalprocedimento',
            name='servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profissionais_habilitados', to='servicos.servico'),
        ),
    ]
