# Generated by Django 5.2.5 on 2025-09-10 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0009_populate_servico_fk'),
        ('core', '0004_add_cargo_tenantuser'),
        ('servicos', '0003_migrate_procedimentos_to_servicos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profissionalprocedimento',
            options={'verbose_name': 'Competência do Profissional em Serviço', 'verbose_name_plural': 'Competências de Profissionais em Serviços'},
        ),
        migrations.RemoveConstraint(
            model_name='profissionalprocedimento',
            name='uniq_competencia_prof_procedimento',
        ),
        migrations.RemoveIndex(
            model_name='profissionalprocedimento',
            name='agendamento_tenant__b551ff_idx',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='procedimento',
        ),
        migrations.RemoveField(
            model_name='profissionalprocedimento',
            name='procedimento',
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='servico',
            field=models.ForeignKey(help_text='Serviço unificado associado', on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='servicos.servico'),
        ),
        migrations.AlterField(
            model_name='profissionalprocedimento',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profissionais_habilitados', to='servicos.servico'),
        ),
        migrations.AddIndex(
            model_name='profissionalprocedimento',
            index=models.Index(fields=['tenant', 'servico'], name='agendamento_tenant__3e84c3_idx'),
        ),
        migrations.AddConstraint(
            model_name='profissionalprocedimento',
            constraint=models.UniqueConstraint(fields=('tenant', 'profissional', 'servico'), name='uniq_competencia_prof_servico'),
        ),
    ]
