# Generated by Django 5.1.5 on 2025-08-14 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('funcionarios', '0001_initial'),
        ('obras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaoObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('atividade', models.CharField(max_length=200, verbose_name='Atividade')),
                ('horas_trabalhadas', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Horas Trabalhadas')),
                ('valor_hora', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor por Hora')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mao_obra', to='funcionarios.funcionario', verbose_name='Funcionário')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mao_obra_registros', to='obras.obra', verbose_name='Obra')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Mão de Obra',
                'verbose_name_plural': 'Registros de Mão de Obra',
                'ordering': ['-data', '-created_at'],
                'indexes': [models.Index(fields=['tenant', 'data'], name='mao_obra_ma_tenant__f452bb_idx'), models.Index(fields=['tenant', 'funcionario'], name='mao_obra_ma_tenant__b7d6a3_idx'), models.Index(fields=['tenant', 'obra'], name='mao_obra_ma_tenant__aace02_idx')],
                'unique_together': {('tenant', 'funcionario', 'obra', 'data')},
            },
        ),
    ]
