# Generated by Django 5.2.5 on 2025-08-19 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_initial'),
        ('core', '0001_initial'),
        ('prontuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('tipo_sanguineo', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True)),
                ('alergias', models.TextField(blank=True, null=True)),
                ('medicamentos_uso', models.TextField(blank=True, null=True)),
                ('doencas_cronicas', models.TextField(blank=True, null=True)),
                ('cirurgias_anteriores', models.TextField(blank=True, null=True)),
                ('tipo_pele', models.CharField(blank=True, choices=[('NORMAL', 'Normal'), ('SECA', 'Seca'), ('OLEOSA', 'Oleosa'), ('MISTA', 'Mista'), ('SENSIVEL', 'Sensível')], max_length=20, null=True)),
                ('fototipo', models.CharField(blank=True, choices=[('I', 'I - Branca (sensível)'), ('II', 'II - Branca (pouco sensível)'), ('III', 'III - Morena Clara (moderadamente sensível)'), ('IV', 'IV - Morena Moderada (pouco sensível)'), ('V', 'V - Morena Escura (resistente)'), ('VI', 'VI - Negra (resistente)')], max_length=10, null=True)),
                ('historico_estetico', models.TextField(blank=True, null=True)),
                ('contato_emergencia_nome', models.CharField(blank=True, max_length=200, null=True)),
                ('contato_emergencia_telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('contato_emergencia_parentesco', models.CharField(blank=True, max_length=50, null=True)),
                ('termo_responsabilidade_assinado', models.BooleanField(default=False)),
                ('data_assinatura_termo', models.DateTimeField(blank=True, null=True)),
                ('lgpd_consentimento', models.BooleanField(default=False)),
                ('data_consentimento_lgpd', models.DateTimeField(blank=True, null=True)),
                ('observacoes_gerais', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_clinico', to='clientes.cliente')),
                ('pessoa_fisica', models.OneToOneField(blank=True, help_text='Redundância leve para acesso rápido a atributos PF', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_clinico', to='clientes.pessoafisica')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfils_clinicos', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Perfil Clínico',
                'verbose_name_plural': 'Perfis Clínicos',
                'constraints': [models.UniqueConstraint(fields=('tenant', 'cliente'), name='unique_perfil_clinico_cliente_tenant')],
            },
        ),
    ]
