# Generated by Django 5.2.5 on 2025-08-19 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_initial'),
        ('prontuarios', '0002_perfilclinico'),
    ]

    operations = [
        migrations.AddField(
            model_name='anamnese',
            name='cliente',
            field=models.ForeignKey(blank=True, help_text='Novo vínculo ao Cliente; fase de transição', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anamneses', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='cliente',
            field=models.ForeignKey(blank=True, help_text='Novo vínculo ao Cliente; fase de transição Paciente -> Cliente', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atendimentos', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='fotoevolucao',
            name='cliente',
            field=models.ForeignKey(blank=True, help_text='Novo vínculo ao Cliente; fase de transição', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fotos_evolucao', to='clientes.cliente'),
        ),
    ]
