# Generated by Django 5.2.5 on 2025-08-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuarios', '0006_fotoevolucao_derivados_indices'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='fotoevolucao',
            new_name='prontuarios_tenant__6dcd04_idx',
            old_name='prontuario_foto_tenant_data_idx',
        ),
        migrations.RenameIndex(
            model_name='fotoevolucao',
            new_name='prontuarios_tenant__3b2fcc_idx',
            old_name='prontuario_foto_tenant_paciente_data_idx',
        ),
        migrations.AddField(
            model_name='fotoevolucao',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fotoevolucao',
            name='video',
            field=models.FileField(blank=True, help_text='Vídeo curto do procedimento (opcional)', null=True, upload_to='prontuarios/videos_evolucao/'),
        ),
    ]
