# Generated by Django 5.2.5 on 2025-08-20 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_initial'),
        ('prontuarios', '0008_merge_0007_conflicts'),
    ]

    operations = [
        # Primeiro: remover o índice que ainda referencia 'paciente' na FotoEvolucao.
        # Usamos SeparateDatabaseAndState para (a) atualizar o estado (RemoveIndex) e (b) executar DROP INDEX condicional
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="DROP INDEX IF EXISTS prontuarios_tenant__3b2fcc_idx;",
                    reverse_sql="-- sem reverse: índice antigo removido definitivamente"
                ),
            ],
            state_operations=[
                migrations.RemoveIndex(
                    model_name='fotoevolucao',
                    name='prontuarios_tenant__3b2fcc_idx',
                ),
            ]
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='anamnese',
            name='paciente',
        ),
        migrations.RemoveField(
            model_name='atendimento',
            name='paciente',
        ),
        migrations.RemoveField(
            model_name='fotoevolucao',
            name='paciente',
        ),
        migrations.RenameField(
            model_name='anamnese',
            old_name='assinatura_paciente',
            new_name='assinatura_cliente',
        ),
        migrations.RemoveField(
            model_name='atendimento',
            name='assinatura_paciente',
        ),
        migrations.RemoveField(
            model_name='atendimento',
            name='satisfacao_paciente',
        ),
        migrations.RemoveField(
            model_name='fotoevolucao',
            name='visivel_paciente',
        ),
        migrations.AddField(
            model_name='atendimento',
            name='assinatura_cliente',
            field=models.TextField(blank=True, null=True, verbose_name='Assinatura Digital do Cliente'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='satisfacao_cliente',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='Satisfação do Cliente (1-10)'),
        ),
        migrations.AddField(
            model_name='fotoevolucao',
            name='visivel_cliente',
            field=models.BooleanField(default=True, verbose_name='Visível para o Cliente'),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anamneses', to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='cliente',
            field=models.ForeignKey(help_text='Vínculo direto ao Cliente (antes Paciente)', on_delete=django.db.models.deletion.CASCADE, related_name='atendimentos', to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='fotoevolucao',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_evolucao', to='clientes.cliente'),
        ),
        migrations.DeleteModel(
            name='Paciente',
        ),
    ]
