# Generated by Django 5.2.5 on 2025-08-22 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0001_initial'),
        ('prontuarios', '0011_rename_fotoevolucao_paciente_to_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='agendamento',
            field=models.ForeignKey(blank=True, help_text='Ligação ao novo Agendamento (beta)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos_clinicos', to='agendamentos.agendamento'),
        ),
    ]
