# Generated by Django 5.2.5 on 2025-08-27 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prontuarios', '0013_add_fotoevolucao_tenant_cliente_index'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='fotoevolucao',
            new_name='prontuarios_tenant__f38f6b_idx',
            old_name='pront_foto_tenant_cliente_idx',
        ),
    ]
