# Generated by Django 5.2.5 on 2025-09-10 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_alter_evento_prioridade_alter_evento_tipo_evento'),
        ('prontuarios', '0014_rename_pront_foto_tenant_cliente_idx_prontuarios_tenant__f38f6b_idx'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='atendimentoslot',
            name='unique_slot_profissional_horario',
        ),
        migrations.RemoveConstraint(
            model_name='atendimentodisponibilidade',
            name='unique_disponibilidade_intervalo_profissional',
        ),
        migrations.RemoveField(
            model_name='atendimentoslot',
            name='disponibilidade',
        ),
        migrations.RemoveField(
            model_name='atendimentoslot',
            name='profissional',
        ),
        migrations.RemoveField(
            model_name='atendimentoslot',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='atendimento',
            name='slot',
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='evento_agenda',
            field=models.ForeignKey(blank=True, help_text='LEGADO: Evento na agenda associado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos_legados', to='agenda.evento'),
        ),
        migrations.DeleteModel(
            name='AtendimentoDisponibilidade',
        ),
        migrations.DeleteModel(
            name='AtendimentoSlot',
        ),
    ]
