# Generated by Django 5.2.5 on 2025-09-10 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuarios', '0015_remove_atendimentoslot_disponibilidade_and_more'),
        ('servicos', '0003_migrate_procedimentos_to_servicos'),
    ]

    operations = [
        migrations.AddField(
            model_name='anamnese',
            name='servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anamneses', to='servicos.servico'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos', to='servicos.servico'),
        ),
    ]
