# Generated by Django 5.2.5 on 2025-09-10 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuarios', '0017_populate_servico_fk'),
        ('servicos', '0003_migrate_procedimentos_to_servicos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anamnese',
            name='procedimento',
        ),
        migrations.RemoveField(
            model_name='atendimento',
            name='procedimento',
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anamneses', to='servicos.servico'),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atendimentos', to='servicos.servico'),
        ),
        migrations.DeleteModel(
            name='Procedimento',
        ),
    ]
