# Generated by Django 5.2.5 on 2025-09-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuarios', '0018_remove_anamnese_procedimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotoevolucao',
            name='video',
            field=models.FileField(blank=True, help_text='Vídeo curto do serviço (opcional)', null=True, upload_to='prontuarios/videos_evolucao/'),
        ),
    ]
