# Generated by Django 5.1.5 on 2025-08-14 21:56

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampoFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Campo')),
                ('label', models.CharField(max_length=200, verbose_name='Rótulo')),
                ('tipo', models.CharField(choices=[('text', 'Texto'), ('textarea', 'Área de Texto'), ('email', 'E-mail'), ('number', 'Número'), ('date', 'Data'), ('datetime', 'Data e Hora'), ('time', 'Hora'), ('select', 'Lista de Seleção'), ('radio', 'Botões de Rádio'), ('checkbox', 'Caixas de Seleção'), ('file', 'Arquivo'), ('image', 'Imagem'), ('url', 'URL'), ('phone', 'Telefone'), ('cpf', 'CPF'), ('cnpj', 'CNPJ'), ('cep', 'CEP'), ('currency', 'Moeda'), ('percentage', 'Porcentagem'), ('rating', 'Avaliação (Estrelas)'), ('color', 'Cor'), ('range', 'Intervalo'), ('hidden', 'Campo Oculto')], max_length=20, verbose_name='Tipo do Campo')),
                ('obrigatorio', models.BooleanField(default=False, verbose_name='Obrigatório')),
                ('placeholder', models.CharField(blank=True, max_length=200, verbose_name='Placeholder')),
                ('help_text', models.CharField(blank=True, max_length=500, verbose_name='Texto de Ajuda')),
                ('valor_padrao', models.TextField(blank=True, verbose_name='Valor Padrão')),
                ('min_length', models.IntegerField(blank=True, null=True, verbose_name='Tamanho Mínimo')),
                ('max_length', models.IntegerField(blank=True, null=True, verbose_name='Tamanho Máximo')),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Mínimo')),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Máximo')),
                ('regex_validacao', models.CharField(blank=True, max_length=500, verbose_name='Regex de Validação')),
                ('opcoes', models.JSONField(blank=True, default=list, help_text='Para campos select, radio e checkbox', verbose_name='Opções')),
                ('css_classes', models.CharField(blank=True, max_length=200, verbose_name='Classes CSS')),
                ('largura_coluna', models.IntegerField(default=12, verbose_name='Largura da Coluna (1-12)')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem')),
                ('grupo', models.CharField(blank=True, max_length=100, verbose_name='Grupo')),
                ('configuracoes_avancadas', models.JSONField(blank=True, default=dict, verbose_name='Configurações Avançadas')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Campo do Formulário',
                'verbose_name_plural': 'Campos do Formulário',
                'ordering': ['ordem', 'criado_em'],
            },
        ),
        migrations.CreateModel(
            name='FormularioDinamico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('ativo', 'Ativo'), ('inativo', 'Inativo'), ('arquivado', 'Arquivado')], default='rascunho', max_length=20, verbose_name='Status')),
                ('publico', models.BooleanField(default=False, verbose_name='Público')),
                ('permite_multiplas_respostas', models.BooleanField(default=False, verbose_name='Permite Múltiplas Respostas')),
                ('requer_login', models.BooleanField(default=True, verbose_name='Requer Login')),
                ('data_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Data de Início')),
                ('data_fim', models.DateTimeField(blank=True, null=True, verbose_name='Data de Fim')),
                ('notificar_nova_resposta', models.BooleanField(default=True, verbose_name='Notificar Nova Resposta')),
                ('emails_notificacao', models.TextField(blank=True, help_text='Um e-mail por linha', verbose_name='E-mails para Notificação')),
                ('cor_tema', models.CharField(default='#007bff', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$')], verbose_name='Cor do Tema')),
                ('css_personalizado', models.TextField(blank=True, verbose_name='CSS Personalizado')),
                ('configuracoes_avancadas', models.JSONField(blank=True, default=dict, verbose_name='Configurações Avançadas')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formularios_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Formulário Dinâmico',
                'verbose_name_plural': 'Formulários Dinâmicos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='CondicaoFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operador', models.CharField(choices=[('equals', 'Igual a'), ('not_equals', 'Diferente de'), ('contains', 'Contém'), ('not_contains', 'Não contém'), ('greater_than', 'Maior que'), ('less_than', 'Menor que'), ('is_empty', 'Está vazio'), ('is_not_empty', 'Não está vazio')], max_length=20, verbose_name='Operador')),
                ('valor_comparacao', models.TextField(blank=True, verbose_name='Valor de Comparação')),
                ('acao', models.CharField(choices=[('show', 'Mostrar'), ('hide', 'Ocultar'), ('require', 'Tornar obrigatório'), ('optional', 'Tornar opcional')], max_length=20, verbose_name='Ação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('campo_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condicoes_destino', to='formularios_dinamicos.campoformulario')),
                ('campo_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condicoes_origem', to='formularios_dinamicos.campoformulario')),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condicoes', to='formularios_dinamicos.formulariodinamico')),
            ],
            options={
                'verbose_name': 'Condição do Formulário',
                'verbose_name_plural': 'Condições do Formulário',
                'ordering': ['criado_em'],
            },
        ),
        migrations.AddField(
            model_name='campoformulario',
            name='formulario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='formularios_dinamicos.formulariodinamico'),
        ),
        migrations.CreateModel(
            name='LogFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=100, verbose_name='Ação')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('dados_anteriores', models.JSONField(blank=True, default=dict)),
                ('dados_novos', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='formularios_dinamicos.formulariodinamico')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log do Formulário',
                'verbose_name_plural': 'Logs dos Formulários',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RespostaFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Token')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('enviado', 'Enviado'), ('em_analise', 'Em Análise'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado'), ('arquivado', 'Arquivado')], default='rascunho', max_length=20, verbose_name='Status')),
                ('dados', models.JSONField(default=dict, verbose_name='Dados da Resposta')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('enviado_em', models.DateTimeField(blank=True, null=True)),
                ('analisado_em', models.DateTimeField(blank=True, null=True)),
                ('observacoes_analise', models.TextField(blank=True, verbose_name='Observações da Análise')),
                ('analisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respostas_analisadas', to=settings.AUTH_USER_MODEL)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='formularios_dinamicos.formulariodinamico')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respostas_formularios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resposta do Formulário',
                'verbose_name_plural': 'Respostas do Formulário',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ArquivoResposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(max_length=100, verbose_name='Campo')),
                ('arquivo', models.FileField(upload_to='formularios_dinamicos/arquivos/%Y/%m/')),
                ('nome_original', models.CharField(max_length=255, verbose_name='Nome Original')),
                ('tamanho', models.IntegerField(verbose_name='Tamanho (bytes)')),
                ('tipo_mime', models.CharField(max_length=100, verbose_name='Tipo MIME')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('resposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='formularios_dinamicos.respostaformulario')),
            ],
            options={
                'verbose_name': 'Arquivo da Resposta',
                'verbose_name_plural': 'Arquivos das Respostas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='TemplateFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Template')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('categoria', models.CharField(max_length=100, verbose_name='Categoria')),
                ('configuracao', models.JSONField(verbose_name='Configuração do Template')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('publico', models.BooleanField(default=False, verbose_name='Público')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Template de Formulário',
                'verbose_name_plural': 'Templates de Formulários',
                'ordering': ['categoria', 'nome'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='campoformulario',
            unique_together={('formulario', 'nome')},
        ),
    ]
