# Generated by Django 5.1.5 on 2025-08-14 21:56

import django.db.models.deletion
import django.utils.timezone
import servicos.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros_gerais', '0001_initial'),
        ('clientes', '0001_initial'),
        ('fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='Slug (URL Amigável)')),
            ],
            options={
                'verbose_name': 'Categoria de Serviço',
                'verbose_name_plural': 'Categorias de Serviços',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='RegraCobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Regra')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('valor_base', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Base')),
                ('valor_minimo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Valor Mínimo (Opcional)')),
                ('incremento', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Incremento Padrão')),
                ('taxa_adicional', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='Taxa Adicional (%)')),
                ('tipo_calculo', models.CharField(choices=[('fixo', 'Valor Fixo'), ('unidade', 'Por Unidade (Baseado na Unidade de Medida)'), ('personalizado', 'Fórmula Personalizada (Avançado)')], default='unidade', max_length=20, verbose_name='Tipo de Cálculo')),
                ('formula_personalizada', models.TextField(blank=True, help_text="Usar 'Q' para quantidade. Ex: (Q * valor_base) + (Q // 10 * taxa_adicional)", null=True, verbose_name='Fórmula Personalizada')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('unidade_medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regras_cobranca', to='cadastros_gerais.unidademedida', verbose_name='Unidade de Medida')),
            ],
            options={
                'verbose_name': 'Regra de Cobrança',
                'verbose_name_plural': 'Regras de Cobrança',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servico', models.CharField(choices=[('OFERTADO', 'Serviço Ofertado (Venda)'), ('RECEBIDO', 'Serviço Contratado (Compra)')], default='OFERTADO', max_length=10, verbose_name='Tipo de Serviço')),
                ('nome_servico', models.CharField(max_length=200, verbose_name='Nome do Serviço')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug (URL Amigável)')),
                ('codigo', models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True, verbose_name='Código do Serviço')),
                ('descricao', models.TextField(verbose_name='Descrição Completa')),
                ('descricao_curta', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição Curta (Resumo)')),
                ('preco_base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Para 'Serviços Ofertados', este é o seu preço de venda. Para 'Serviços Contratados', este é apenas um valor de referência.", max_digits=10, verbose_name='Preço Base (Padrão/Venda)')),
                ('tempo_estimado', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tempo Estimado de Execução')),
                ('prazo_entrega', models.PositiveIntegerField(blank=True, null=True, verbose_name='Prazo de Entrega (em dias úteis)')),
                ('materiais_inclusos', models.TextField(blank=True, null=True, verbose_name='Materiais Inclusos')),
                ('materiais_nao_inclusos', models.TextField(blank=True, null=True, verbose_name='Materiais Não Inclusos')),
                ('requisitos', models.TextField(blank=True, null=True, verbose_name='Requisitos para o Cliente')),
                ('disponivel_online', models.BooleanField(default=True, verbose_name='Disponível para Contratação Online')),
                ('requer_visita_tecnica', models.BooleanField(default=False, verbose_name='Requer Visita Técnica Prévia')),
                ('requer_aprovacao', models.BooleanField(default=False, verbose_name='Requer Aprovação de Orçamento Prévio')),
                ('palavras_chave', models.CharField(blank=True, help_text='Separadas por vírgula', max_length=255, null=True, verbose_name='Palavras-chave (SEO)')),
                ('destaque', models.BooleanField(default=False, verbose_name='Serviço em Destaque')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo (Visível no Catálogo)')),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Cadastro')),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('imagem_principal', models.ImageField(blank=True, null=True, upload_to='servicos/principais/', verbose_name='Imagem Principal')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicos', to='servicos.categoriaservico', verbose_name='Categoria')),
                ('clientes', models.ManyToManyField(blank=True, related_name='servicos_ofertados', to='clientes.cliente', verbose_name='Clientes Associados a este Serviço')),
                ('regra_cobranca', models.ForeignKey(blank=True, help_text="Regra de cobrança para seus 'Serviços Ofertados'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicos_padrao', to='servicos.regracobranca', verbose_name='Regra de Cobrança (Padrão/Venda)')),
            ],
            options={
                'verbose_name': 'Serviço (Catálogo)',
                'verbose_name_plural': 'Serviços (Catálogo)',
                'ordering': ['nome_servico'],
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=100, verbose_name='Nome do Cliente')),
                ('email_cliente', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email do Cliente (Opcional)')),
                ('nota', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Nota (1 a 5)')),
                ('comentario', models.TextField(verbose_name='Comentário')),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Avaliação')),
                ('aprovado', models.BooleanField(default=False, verbose_name='Aprovado para Exibição')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='servicos.servico')),
            ],
            options={
                'verbose_name': 'Avaliação de Serviço',
                'verbose_name_plural': 'Avaliações de Serviços',
                'ordering': ['-data_avaliacao'],
            },
        ),
        migrations.CreateModel(
            name='ServicoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título do Documento')),
                ('arquivo', models.FileField(upload_to=servicos.models.servico_documento_path, verbose_name='Arquivo')),
                ('tipo', models.CharField(choices=[('contrato', 'Contrato Modelo'), ('termo', 'Termo de Serviço'), ('manual', 'Manual de Uso/Instruções'), ('certificado', 'Certificado de Garantia'), ('portfolio', 'Portfólio/Case de Sucesso'), ('outro', 'Outro')], default='outro', max_length=50, verbose_name='Tipo de Documento')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_anexos', to='servicos.servico')),
            ],
            options={
                'verbose_name': 'Documento do Serviço',
                'verbose_name_plural': 'Documentos do Serviço',
                'ordering': ['servico', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='ServicoFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_base_fornecedor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Base do Fornecedor')),
                ('codigo_fornecedor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código do Serviço no Fornecedor')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fornecedores.fornecedor')),
                ('regra_cobranca_fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicos_fornecedor', to='servicos.regracobranca', verbose_name='Regra de Cobrança do Fornecedor')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicos.servico')),
            ],
            options={
                'verbose_name': 'Fornecedor do Serviço',
                'verbose_name_plural': 'Fornecedores do Serviço',
                'ordering': ['fornecedor__pessoajuridica__razao_social', 'fornecedor__pessoafisica__nome_completo'],
                'unique_together': {('servico', 'fornecedor')},
            },
        ),
        migrations.AddField(
            model_name='servico',
            name='fornecedores',
            field=models.ManyToManyField(related_name='servicos_prestados', through='servicos.ServicoFornecedor', to='fornecedores.fornecedor', verbose_name='Fornecedores'),
        ),
        migrations.CreateModel(
            name='ServicoImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to=servicos.models.servico_imagem_path, verbose_name='Imagem')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Título (Opcional)')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição (Opcional)')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens_adicionais', to='servicos.servico')),
            ],
            options={
                'verbose_name': 'Imagem Adicional do Serviço',
                'verbose_name_plural': 'Imagens Adicionais do Serviço',
                'ordering': ['servico', 'ordem', 'data_upload'],
            },
        ),
    ]
