# Generated by Django 5.2.5 on 2025-09-10 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_cargo_tenantuser'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicoClinico',
            fields=[
                ('servico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='perfil_clinico', serialize=False, to='servicos.servico', verbose_name='Serviço Base')),
                ('duracao_estimada', models.DurationField(verbose_name='Duração Estimada')),
                ('requisitos_pre_procedimento', models.TextField(blank=True, null=True)),
                ('contraindicacoes', models.TextField(blank=True, null=True)),
                ('cuidados_pos_procedimento', models.TextField(blank=True, null=True)),
                ('requer_anamnese', models.BooleanField(default=True)),
                ('requer_termo_consentimento', models.BooleanField(default=True)),
                ('permite_fotos_evolucao', models.BooleanField(default=True)),
                ('intervalo_minimo_sessoes', models.PositiveIntegerField(default=7, verbose_name='Intervalo Mínimo entre Sessões (dias)')),
            ],
            options={
                'verbose_name': 'Perfil Clínico do Serviço',
                'verbose_name_plural': 'Perfis Clínicos de Serviços',
            },
        ),
        migrations.AddField(
            model_name='servico',
            name='is_clinical',
            field=models.BooleanField(default=False, help_text='Marque se este serviço tiver características de saúde/estética.', verbose_name='É um Serviço Clínico?'),
        ),
        migrations.AddField(
            model_name='servico',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='core.tenant', verbose_name='Empresa (Tenant)'),
        ),
    ]
