# Generated by Django 5.2.5 on 2025-08-20 14:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('ativo', models.BooleanField(default=True)),
                ('is_admin_portal', models.BooleanField(default=False)),
                ('data_concessao', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_ultimo_acesso', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas_portal', to='clientes.cliente')),
                ('concedido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_cliente_concedidas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas_cliente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conta Cliente',
                'verbose_name_plural': 'Contas Cliente',
                'db_table': 'portal_cliente_conta',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['cliente', 'ativo'], name='portal_clie_cliente_2c42fc_idx'), models.Index(fields=['usuario', 'ativo'], name='portal_clie_usuario_695173_idx')],
                'unique_together': {('cliente', 'usuario')},
            },
        ),
    ]
