# Generated by Django 5.2.5 on 2025-08-20 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
        ('portal_cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoPortalCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('titulo_externo', models.CharField(blank=True, max_length=160)),
                ('descricao_externa', models.TextField(blank=True)),
                ('expiracao_visualizacao', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='portal_cliente.contacliente')),
                ('documento_versao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exposicoes_cliente', to='documentos.documentoversao')),
            ],
            options={
                'verbose_name': 'Documento Portal Cliente',
                'verbose_name_plural': 'Documentos Portal Cliente',
                'db_table': 'portal_cliente_doc',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['conta', 'ativo'], name='portal_clie_conta_i_32c6e6_idx'), models.Index(fields=['ativo'], name='portal_clie_ativo_f9f724_idx')],
                'constraints': [models.UniqueConstraint(fields=('conta', 'documento_versao'), name='unique_doc_portal_cliente')],
            },
        ),
    ]
