# Generated by Django 5.1.5 on 2025-08-14 21:56

import clientes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcessoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin_portal', models.BooleanField(default=False, verbose_name='É Administrador do Portal?')),
                ('data_concessao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Acesso de Cliente ao Portal',
                'verbose_name_plural': 'Acessos de Clientes ao Portal',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_interno', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código Interno')),
                ('tipo', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], default='PF', max_length=2, verbose_name='Tipo de Cliente')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo'), ('suspended', 'Suspenso')], default='active', max_length=10, verbose_name='Status')),
                ('imagem_perfil', models.ImageField(blank=True, null=True, upload_to=clientes.models.cliente_imagem_path, verbose_name='Foto do Perfil / Logo')),
                ('portal_ativo', models.BooleanField(default=False, help_text='Habilita o acesso do cliente e seus usuários ao portal do sistema.', verbose_name='Portal do Cliente Ativo?')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail Principal')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone Principal')),
                ('telefone_secundario', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone Secundário')),
                ('cep', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP')),
                ('logradouro', models.CharField(blank=True, max_length=255, null=True, verbose_name='Logradouro')),
                ('numero', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado (UF)')),
                ('pais', models.CharField(blank=True, default='Brasil', max_length=50, null=True, verbose_name='País')),
                ('data_cadastro', models.DateField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('ativo', models.BooleanField(default=True, editable=False, verbose_name='Ativo (Legado)')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TEL', 'Telefone Fixo'), ('CEL', 'Celular'), ('EMAIL', 'E-mail'), ('WHATS', 'WhatsApp'), ('SITE', 'Website'), ('OUTRO', 'Outro')], max_length=10, verbose_name='Tipo de Contato')),
                ('valor', models.CharField(max_length=254, verbose_name='Contato (Telefone, Email, etc.)')),
                ('nome_contato_responsavel', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Contato (Responsável)')),
                ('cargo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo')),
                ('principal', models.BooleanField(default=False, verbose_name='Contato Principal deste Tipo')),
                ('observacao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Observação')),
            ],
            options={
                'verbose_name': 'Contato Adicional',
                'verbose_name_plural': 'Contatos Adicionais',
            },
        ),
        migrations.CreateModel(
            name='DocumentoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CPF', 'CPF'), ('RG', 'RG'), ('CNH', 'CNH'), ('COMP_RES', 'Comprovante de Residência'), ('CONTRATO', 'Contrato'), ('CNPJ_CARTAO', 'Cartão CNPJ'), ('CONT_SOC', 'Contrato Social/Alterações'), ('CERT_NEG', 'Certidão Negativa'), ('ALVARA', 'Alvará de Funcionamento'), ('PROCURACAO', 'Procuração'), ('OUTRO', 'Outro')], max_length=15, verbose_name='Tipo de Documento')),
                ('arquivo', models.FileField(upload_to=clientes.models.cliente_documento_path, verbose_name='Arquivo')),
                ('nome_documento', models.CharField(max_length=200, verbose_name='Nome do Documento (Ex: Contrato Assinado)')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição/Observações')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('data_validade', models.DateField(blank=True, null=True, verbose_name='Data de Validade (se aplicável)')),
            ],
            options={
                'verbose_name': 'Documento do Cliente',
                'verbose_name_plural': 'Documentos dos Clientes',
            },
        ),
        migrations.CreateModel(
            name='EnderecoAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('COM', 'Comercial'), ('RES', 'Residencial'), ('ENT', 'Entrega'), ('COB', 'Cobrança'), ('FILIAL', 'Filial'), ('OUTRO', 'Outro')], max_length=10, verbose_name='Tipo de Endereço')),
                ('logradouro', models.CharField(max_length=200, verbose_name='Logradouro')),
                ('numero', models.CharField(max_length=20, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado (UF)')),
                ('cep', models.CharField(max_length=10, verbose_name='CEP')),
                ('pais', models.CharField(blank=True, default='Brasil', max_length=50, null=True, verbose_name='País')),
                ('ponto_referencia', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ponto de Referência')),
                ('principal', models.BooleanField(default=False, verbose_name='Endereço Principal deste Tipo')),
            ],
            options={
                'verbose_name': 'Endereço Adicional',
                'verbose_name_plural': 'Endereços Adicionais',
            },
        ),
    ]
