# Generated by Django 5.1.5 on 2025-08-14 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='acessocliente',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acessos_cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pessoafisica', serialize=False, to='clientes.cliente')),
                ('nome_completo', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=20, null=True, verbose_name='RG')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, null=True, verbose_name='Sexo')),
                ('naturalidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Naturalidade (Cidade de Nascimento)')),
                ('nome_mae', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome da Mãe')),
                ('nome_pai', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Pai')),
                ('estado_civil', models.CharField(blank=True, choices=[('S', 'Solteiro(a)'), ('C', 'Casado(a)'), ('D', 'Divorciado(a)'), ('V', 'Viúvo(a)'), ('U', 'União Estável'), ('O', 'Outro')], max_length=1, null=True, verbose_name='Estado Civil')),
                ('profissao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Profissão')),
                ('nacionalidade', models.CharField(blank=True, default='Brasileira', max_length=100, null=True, verbose_name='Nacionalidade')),
            ],
            options={
                'verbose_name': 'Pessoa Física',
                'verbose_name_plural': 'Pessoas Físicas',
            },
        ),
        migrations.CreateModel(
            name='PessoaJuridica',
            fields=[
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pessoajuridica', serialize=False, to='clientes.cliente')),
                ('razao_social', models.CharField(max_length=200, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome Fantasia')),
                ('cnpj', models.CharField(max_length=18, verbose_name='CNPJ')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Estadual')),
                ('inscricao_municipal', models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Municipal')),
                ('data_fundacao', models.DateField(blank=True, null=True, verbose_name='Data de Fundação')),
                ('ramo_atividade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ramo de Atividade')),
                ('porte_empresa', models.CharField(blank=True, max_length=50, null=True, verbose_name='Porte da Empresa')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Site / Website')),
                ('email_financeiro', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail do Financeiro')),
                ('telefone_financeiro', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone do Financeiro')),
            ],
            options={
                'verbose_name': 'Pessoa Jurídica',
                'verbose_name_plural': 'Pessoas Jurídicas',
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='core.tenant', verbose_name='Empresa (Tenant)'),
        ),
        migrations.AddField(
            model_name='acessocliente',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acessos', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='contato',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos_adicionais', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='documentocliente',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_cliente', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='enderecoadicional',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enderecos_adicionais', to='clientes.cliente'),
        ),
        migrations.AlterUniqueTogether(
            name='cliente',
            unique_together={('tenant', 'codigo_interno'), ('tenant', 'email')},
        ),
        migrations.AlterUniqueTogether(
            name='acessocliente',
            unique_together={('cliente', 'usuario')},
        ),
    ]
