# Generated by Django 5.1.5 on 2025-08-14 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Número')),
                ('data_pedido', models.DateField(verbose_name='Data do Pedido')),
                ('data_entrega_prevista', models.DateField(verbose_name='Data de Entrega Prevista')),
                ('data_entrega_real', models.DateField(blank=True, null=True, verbose_name='Data de Entrega Real')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Total')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('em_transito', 'Em Trânsito'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], default='pendente', max_length=20, verbose_name='Status')),
                ('forma_pagamento', models.CharField(choices=[('a_vista', 'À Vista'), ('30_dias', '30 Dias'), ('60_dias', '60 Dias'), ('90_dias', '90 Dias'), ('parcelado', 'Parcelado')], default='30_dias', max_length=20, verbose_name='Forma de Pagamento')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'ordering': ['-data_pedido'],
            },
        ),
    ]
