# Generated by Django 5.1.5 on 2025-08-14 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
        ('fornecedores', '0001_initial'),
        ('obras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='fornecedores.fornecedor', verbose_name='Fornecedor'),
        ),
        migrations.AddField(
            model_name='compra',
            name='obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='obras.obra', verbose_name='Obra'),
        ),
    ]
