# Generated by Django 5.1.5 on 2025-08-14 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treinamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(verbose_name='Data de Término')),
                ('carga_horaria', models.PositiveIntegerField(verbose_name='Carga Horária (horas)')),
                ('local', models.CharField(max_length=200, verbose_name='Local')),
                ('material', models.FileField(blank=True, null=True, upload_to='treinamentos/', verbose_name='Material')),
                ('instrutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treinamentos_ministrados', to='funcionarios.funcionario', verbose_name='Instrutor')),
            ],
            options={
                'verbose_name': 'Treinamento',
                'verbose_name_plural': 'Treinamentos',
                'ordering': ['-data_inicio'],
            },
        ),
    ]
